### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by Coloryr** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#102]
```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Skip[TSource](IEnumerable`1 source, Int32 count)
   at HttpMultipartParser.StreamingMultipartFormDataParser.DetectBoundary(RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.Run()
   at HttpMultipartParser.MultipartFormDataParser.ParseStream(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize, String[] binaryMimeTypes)
   at HttpMultipartParser.MultipartFormDataParser.Parse(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize, String[] binaryMimeTypes)
   at ColoryrServer.ASP.ASPServer.POSTBack(HttpContext context) in G:\code\ColoryrWork\ColoryrServer\ASP\Program.cs:line 378
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by Jericho** [comment]
Thanks for the stack trace but I'm afraid that's not enough to allow me to reproduce. Do you have code sample and/or sample data that I can use?
